import base_datos.UsuarioDAO;
import entidades.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erick
 */
public class jFrameGestionarUsuarios extends javax.swing.JFrame {
    private UsuarioDAO dao;  // Instancia del DAO para conectar con BD
    private int idUsuarioSeleccionado = -1;  // Para actualizar/eliminar (ID del usuario seleccionado)
    /**
     * Creates new form jFrameGestionarUsuarios
     */
    public jFrameGestionarUsuarios() {
        initComponents();
        
       dao = new UsuarioDAO();  // Inicializa el DAO
       setLocationRelativeTo(null);  // Centra la ventana 
       limpiarCampos();  // Limpia los campos al inicio
       listarUsuarios();  // Carga la lista inicial en la JTable

    }
    private Usuario obtenerUsuarioDeCampos() {
        // Validaciones básicas
        if (txtNombres.getText().trim().isEmpty() || txtApellidos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llena nombres y apellidos obligatorios.");
        return null;
        }
        if (txtCorreo.getText().trim().isEmpty() || txtId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llena correo e identificador.");
        return null;
    }
        // Crea instancia de Usuario usando constructor vacío
         Usuario u = new Usuario();  // Usa tu clase Usuario
        
        // Mapea campos del JFrame a setters de Usuario
            u.setId(idUsuarioSeleccionado > 0 ? idUsuarioSeleccionado : 0);  // ID de BD (para actualizar; 0 para nuevo)
            u.setNombres(txtNombres.getText().trim());
            u.setApellidos(txtApellidos.getText().trim());
            u.setCorreoElectronico(txtCorreo.getText().trim());
            u.setCargo((String) cbCargos.getSelectedItem());  // Del JComboBox
            u.setIdentificador(txtId.getText().trim());  // txtId es identificador (string)
            u.setContrasena(txtContraseña.getText().trim());  // String plano; integra con Password en setter si necesitas
    
        return u;  // Retorna el Usuario listo para el DAO
}
    //Limpia los campos del formulario
    private void limpiarCampos() {
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCorreo.setText("");
        cbCargos.setSelectedIndex(0);  // Selecciona primer cargo por defecto
        txtId.setText("");  // Identificador
        txtContraseña.setText("");
        idUsuarioSeleccionado = -1;
        // Deshabilita botones de editar si quieres
        // btnActualizar.setEnabled(false);
        // btnEliminar.setEnabled(false);
    }
    
    //Carga todos los usuarios desde la BD y los muestra en la JTable.
     private void listarUsuarios() {
        List<Usuario> usuarios = dao.listarUsuarios();
        DefaultTableModel modelo = (DefaultTableModel) jTablaUsuarios.getModel();
        modelo.setRowCount(0);  // Limpia la tabla
        
        for (Usuario u : usuarios) {
            modelo.addRow(new Object[]{
                u.getNombres(),
                u.getApellidos(),
                u.getCorreoElectronico(),
                u.getCargo(),
                u.getIdentificador(),
                u.getContrasena()// Podemos eliminar esta linea si no queremos mostrar la contraseña en la tabla, solo por seguridad
            });
        }
    }
    //Carga datos de la fila seleccionada en la tabla a los campos (para editar).


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        cbCargos = new javax.swing.JComboBox<>();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaUsuarios = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionar Usuarios");

        jLabel1.setText("Nombres :");

        jLabel2.setText("Apellidos :");

        jLabel3.setText("Correo Electrónico :");

        jLabel4.setText("Cargo :");

        jLabel5.setText("Identificador :");

        jLabel6.setText("Contraseña :");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        cbCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Técnico", "Programador", "Cliente" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jTablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombres", "Apellidos", "Correo Electrónico", "Cargo", "Identificador", "Contraseña"
            }
        ));
        jTablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaUsuarios);

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtras)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                            .addComponent(txtApellidos)
                                            .addComponent(txtId)
                                            .addComponent(txtContraseña)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addComponent(cbCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Usuario u = obtenerUsuarioDeCampos();
        if (u.getNombres().isEmpty() || u.getApellidos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llena nombres y apellidos.");
            return;
        }
        if (dao.insertarUsuario(u)) {
            JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente en BD.");
            listarUsuarios();  // Actualiza la tabla
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar. Verifica datos (ej: identificador único).");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        System.out.println("ID antes de actualizar: " + idUsuarioSeleccionado); // para depurar
        if (idUsuarioSeleccionado <= 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un usuario de la tabla para actualizar.");
            return;
        }
        Usuario u = obtenerUsuarioDeCampos();
        if (dao.actualizarUsuario(u)) {
            JOptionPane.showMessageDialog(this, "Usuario actualizado en BD.");
            listarUsuarios();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idUsuarioSeleccionado <= 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un usuario de la tabla.");
        return;
    }
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
        if (dao.eliminarUsuario(idUsuarioSeleccionado)) {  // Llama a DAO con ID numérico
            JOptionPane.showMessageDialog(this, "Usuario eliminado de la BD.");
            listarUsuarios();  // Recarga tabla
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar.");
        }
      }    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String texto = txtBuscar.getText().trim();
       if (texto.isEmpty()) {
        listarUsuarios();  // Si vacío, muestra todos
        return;
    }
    
    // Llama a un método de búsqueda en DAO 
        List<Usuario> resultados = dao.buscarUsuarios(texto);  // Busca por nombres, identificador, etc.
        DefaultTableModel modelo = (DefaultTableModel) jTablaUsuarios.getModel();
        modelo.setRowCount(0);  // Limpia tabla
    
    for (Usuario u : resultados) {
        modelo.addRow(new Object[]{
            u.getNombres(),
            u.getApellidos(),
            u.getCorreoElectronico(),
            u.getCargo(),
            u.getIdentificador()
        });
    }
    
    if (resultados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se encontró ningún usuario.");
        } else {
        JOptionPane.showMessageDialog(this, "Se encontraron " + resultados.size() + " resultados.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        jFrameMenuAdmin atras = new jFrameMenuAdmin();
        atras.setVisible(true);
        atras.setLocationRelativeTo(null);
        this.dispose();//Cierra la ventana actual
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jTablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaUsuariosMouseClicked
        int fila = jTablaUsuarios.getSelectedRow();
    if (fila >= 0) {
        String identificador = jTablaUsuarios.getValueAt(fila, 4).toString();
        Usuario u = dao.buscarPorIdentificador(identificador);
        if (u != null) {
            idUsuarioSeleccionado = u.getId();
            txtNombres.setText(u.getNombres());
            txtApellidos.setText(u.getApellidos());
            txtCorreo.setText(u.getCorreoElectronico());
            cbCargos.setSelectedItem(u.getCargo());
            txtId.setText(u.getIdentificador());
            txtContraseña.setText("");
        }
    }
    }//GEN-LAST:event_jTablaUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameGestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameGestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameGestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameGestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameGestionarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbCargos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaUsuarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
