/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capa_vista;

import base_datos.ConexionBD;
import capa_controladora.UsuarioController;
import entidades.TipoUsuario;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import java.sql.Connection;

/**
 *
 * @author Adam
 */
public class jFrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form jFrameLogin
     */
    public jFrameLogin() {
        initComponents();
        //
        lblCrearCuenta.setText("<html><u>Crear cuenta</u></html>");
        lblCrearCuenta.setForeground(Color.BLUE);
        lblCrearCuenta.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtContraseña = new javax.swing.JTextField();
        lblCrearCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setText("Usuario");

        lblContraseña.setText("Contraseña");

        btnLogin.setText("Iniciar sesion");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblCrearCuenta.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblCrearCuenta.setText("Crear cuenta");
        lblCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearCuentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblContraseña))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblCrearCuenta)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(lblCrearCuenta)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // 1. Obtener las credenciales ingresadas por el usuario
        String identificador = txtUsuario.getText();
        String claveAcceso = txtContraseña.getText();

        // 2. Establecer la conexión a la base de datos
        // NOTA: Se asume que 'ConexionBD.conectar()' devuelve una conexión válida.
        Connection con = ConexionBD.conectar();

        // 3. Usar el controlador para verificar las credenciales y obtener el cargo
        UsuarioController userController = new UsuarioController(con);
        TipoUsuario cargo = userController.introducirCredenciales(identificador, claveAcceso);

        // 4. Procesar el resultado del login
        if (cargo != null) {

            // Credenciales correctas: Se obtiene el cargo y se elimina cualquier espacio extra.
            String tipoCargo = cargo.getCargo().trim();
            JOptionPane.showMessageDialog(this, "Bienvenido, acceso como: " + tipoCargo);

            // 5. Redireccionar al usuario según su cargo (Rol)
            if (tipoCargo.equalsIgnoreCase("Admin")) {
                new jFrameMenuAdmin().setVisible(true);
                this.dispose();

            } else if (tipoCargo.equalsIgnoreCase("Programador")) {
                new jFrameMenuTecnico().setVisible(true); // Programador usa el mismo menú que el Técnico
                this.dispose();

            } else if (tipoCargo.equalsIgnoreCase("Técnico")) {
                new jFrameMenuTecnico().setVisible(true);
                this.dispose();

            } else if (tipoCargo.equalsIgnoreCase("Cliente")) {
                new jFrameMenuCliente().setVisible(true); // <-- ¡Esta es la línea corregida que faltaba!
                this.dispose();

            } else {
                // Cargo válido, pero sin interfaz definida
                JOptionPane.showMessageDialog(this, "Cargo no reconocido: " + tipoCargo);
            }

        } else {
            // Credenciales incorrectas: Mostrar mensaje de error
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentaMouseClicked
        // enlace para pantalla crear cuenta
        jFrameCrearCuenta crearCuenta = new jFrameCrearCuenta();
        crearCuenta.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblCrearCuentaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCrearCuenta;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
