package capa_vista;

import capa_vista.jFrameMenuTecnico;
import capa_controladora.SolicitudController;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author RYZEN
 */
public class jFrameSeguimientoSolicitud extends javax.swing.JFrame {

// Referencia al Controller inyectada
    private SolicitudController controlador;

    public jFrameSeguimientoSolicitud() {
        initComponents();
    }

    // --- GETTERS PARA COMBOBOXES ---
    public javax.swing.JComboBox<String> getCbCargo() {
        return cbCargo;
    }

    public javax.swing.JComboBox<String> getCbNombre() {
        return cbNombre;
    }

    public javax.swing.JComboBox<String> getCbNTicket() {
        return cbNTicket;
    }

    public javax.swing.JComboBox<String> getCbEstadoSolicitud() {
        return cbEstadoSolicitud;
    }

    // --- GETTERS PARA CAMPOS DE TEXTO ---
    public javax.swing.JTextField getTxtFechaCreacion() {
        return txtFechaCreacion;
    }

    public javax.swing.JTextField getTxtTipoServicio() {
        return txtTipoServicio;
    }

    public javax.swing.JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public javax.swing.JTextField getTxtNivelPrioridad() {
        return txtNivelPrioridad;
    }

    // --- GETTER PARA BOTÓN (Necesario para añadir el ActionListener en el Controller) ---
    public javax.swing.JButton getBtnActualizarSolicitud() {
        return btnActualizarSolicitud;
    }

    // --- SETTER para inyectar el Controller ---
    public void setControlador(SolicitudController controlador) {
        this.controlador = controlador;
    }

    /*
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        lblCargo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNTicket = new javax.swing.JLabel();
        lblFechaCreacion = new javax.swing.JLabel();
        lblTipoServicio = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblEstadoSolicitud = new javax.swing.JLabel();
        lblNivelPrioridad = new javax.swing.JLabel();
        btnActualizarSolicitud = new javax.swing.JButton();
        btnCancelarSolicitud = new javax.swing.JButton();
        cbCargo = new javax.swing.JComboBox<>();
        cbNombre = new javax.swing.JComboBox<>();
        cbNTicket = new javax.swing.JComboBox<>();
        cbEstadoSolicitud = new javax.swing.JComboBox<>();
        txtFechaCreacion = new javax.swing.JTextField();
        txtTipoServicio = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtNivelPrioridad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lblCargo.setText("Cargo");

        lblNombre.setText("Nombre");

        lblNTicket.setText("N° ticket");

        lblFechaCreacion.setText("Fecha Creacion");

        lblTipoServicio.setText("Tipo Servicio");

        lblDescripcion.setText("Descripcion");

        lblEstadoSolicitud.setText("Estado de Solicitud");

        lblNivelPrioridad.setText("Nivel de prioridad");

        btnActualizarSolicitud.setText("Actualizar Solicitud");
        btnActualizarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSolicitudActionPerformed(evt);
            }
        });

        btnCancelarSolicitud.setText("Cancelar Solicitud");
        btnCancelarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSolicitudActionPerformed(evt);
            }
        });

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNTicket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbEstadoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizarSolicitud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarSolicitud))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEstadoSolicitud)
                            .addComponent(lblNivelPrioridad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoServicio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaCreacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNTicket, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbEstadoSolicitud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoServicio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaCreacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNombre, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNTicket, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNivelPrioridad)
                            .addComponent(cbCargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(lblCargo)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNTicket)
                    .addComponent(cbNTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaCreacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoServicio)
                    .addComponent(txtTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoSolicitud)
                    .addComponent(cbEstadoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelPrioridad)
                    .addComponent(txtNivelPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarSolicitud)
                    .addComponent(btnCancelarSolicitud))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if (controlador != null) {
            controlador.irAtras();
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnActualizarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSolicitudActionPerformed
        if (controlador != null) {
            controlador.actualizarDesdeVista();
        }        
    }//GEN-LAST:event_btnActualizarSolicitudActionPerformed

    private void btnCancelarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSolicitudActionPerformed
        if (controlador != null) {
            controlador.cancelarSolicitudDesdeVista();
        }
    }//GEN-LAST:event_btnCancelarSolicitudActionPerformed


    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameSeguimientoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameSeguimientoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameSeguimientoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameSeguimientoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarSolicitud;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCancelarSolicitud;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbEstadoSolicitud;
    private javax.swing.JComboBox<String> cbNTicket;
    private javax.swing.JComboBox<String> cbNombre;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstadoSolicitud;
    private javax.swing.JLabel lblFechaCreacion;
    private javax.swing.JLabel lblNTicket;
    private javax.swing.JLabel lblNivelPrioridad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipoServicio;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtNivelPrioridad;
    private javax.swing.JTextField txtTipoServicio;
    // End of variables declaration//GEN-END:variables
}
